version: '3.3'

volumes:
  pg_data:
  static_volume:
  static_media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: asumasuma/foodgram_backend
    volumes:
      - static_volume:/backend_static
      - static_media:/app/media
  frontend:
    image: asumasuma/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: asumasuma/foodgram_gateway
    volumes:
      - static_volume:/static/
      - static_media:/app/media
    ports:
      - 80:80