# Generated by Django 3.2 on 2023-09-05 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230904_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимум 1'), django.core.validators.MaxValueValidator(999, 'Максимум 999 единиц')], verbose_name='Количество'),
        ),
    ]
